name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Checks Markdown files for lint errors
      - name: Markdown Linting Action
        uses: avto-dev/markdown-lint@v1.1.0
        with:
          args: './*.md'

      # Checks YAML files for lint errors
      - name: YAML Linting Action
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_strict: false
